spring:
  datasource:
    url: jdbc:mariadb://localhost:2306/security
    username: security
    password: security
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    defer-datasource-initialization: true