spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/kised
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    defer-datasource-initialization: true

logging:
  level:
    root: info
    org:
      springframework:
        security: DEBUG